export const ARTICLES = [
  {
    slug: '50-beautiful-islamic-girl-names-starting-with-f',
    title: '50 Beautiful Islamic Girl Names Starting with F',
    href: '/blog/50-beautiful-islamic-girl-names-starting-with-f',
    tag: 'Girl Names',
    tagBg: '#FCE8F0',
    tagText: '#A0305A',
    date: 'June 10, 2026',
    readTime: '6 min',
    views: '12,400',
    arabicLetter: 'فـ',
    gradientFrom: '#A0305A',
    gradientTo: '#D4607A',
    excerpt: 'From Fatima to Firdaus — explore 50 meaningful girl names starting with the Arabic letter Fa, with full meanings, Arabic script, and origins.',
    featured: true,
    category: 'girl',
    comingSoon: false,
  },
  {
    slug: 'top-30-quranic-names-for-baby-boys-in-2026',
    title: 'Top 30 Quranic Names for Baby Boys in 2026',
    href: '/blog/top-30-quranic-names-for-baby-boys-in-2026',
    tag: 'Quranic Names',
    tagBg: '#D1FAE5',
    tagText: '#065F46',
    date: 'June 11, 2026',
    readTime: '7 min',
    arabicLetter: 'قـ',
    gradientFrom: '#1A4F8A',
    gradientTo: '#2E6DB4',
    excerpt: 'Names directly from the Quran carry immense blessing. Compiled with verse references.',
    category: 'boy',
    comingSoon: false,
  },
  {
    slug: 'how-to-choose-an-islamic-name',
    title: 'How to Choose an Islamic Name — Complete Guide for Parents',
    href: '/blog/how-to-choose-an-islamic-name',
    tag: 'Naming Guide',
    tagBg: '#F0DEB0',
    tagText: '#7A5A10',
    date: 'June 3, 2026',
    readTime: '5 min',
    arabicLetter: 'نـ',
    gradientFrom: '#7A5A10',
    gradientTo: '#C4922A',
    excerpt: 'What Islam says about naming: Sunnah, what to avoid, and how to pick a name that lasts.',
    category: 'tips',
    comingSoon: false,
  },
  {
    slug: 'modern-arabic-girl-names-that-sound-beautiful',
    title: 'Modern Arabic Girl Names That Sound Beautiful in English Too',
    href: '/blog/modern-arabic-girl-names-that-sound-beautiful',
    tag: 'Girl Names',
    tagBg: '#FCE8F0',
    tagText: '#A0305A',
    date: 'May 28, 2026',
    readTime: '5 min',
    arabicLetter: 'مـ',
    gradientFrom: '#A0305A',
    gradientTo: '#D4607A',
    excerpt: 'Elegant, meaningful names that work perfectly in Karachi, London, or Toronto.',
    category: 'girl',
    comingSoon: false,
  },
  {
    slug: 'rare-islamic-boy-names-with-deep-meanings',
    title: 'Rare Islamic Boy Names with Deep, Powerful Meanings',
    href: '/blog/rare-islamic-boy-names-with-deep-meanings',
    tag: 'Boy Names',
    tagBg: '#E3EEF9',
    tagText: '#1A4F8A',
    date: 'May 22, 2026',
    readTime: '6 min',
    arabicLetter: 'زـ',
    gradientFrom: '#2D4A6A',
    gradientTo: '#4A7FA5',
    excerpt: 'Distinctive, strong Arabic boy names rarely seen in standard lists — with full meanings.',
    category: 'boy',
    comingSoon: false,
  },
  {
    slug: 'names-meaning-light-in-the-quran',
    title: 'Names Meaning Light in the Quran — Noor, Zia, and More',
    href: '/blog/names-meaning-light-in-the-quran',
    tag: 'Quranic Names',
    tagBg: '#D1FAE5',
    tagText: '#065F46',
    date: 'May 15, 2026',
    readTime: '6 min',
    arabicLetter: 'عـ',
    gradientFrom: '#3D3D1E',
    gradientTo: '#6B6B2E',
    excerpt: 'Light is one of the most sacred themes in the Quran. Names rooted in Noor and radiance.',
    category: 'quran',
    comingSoon: false,
  },
  {
    slug: '50-islamic-girl-names-starting-with-s',
    title: '50 Islamic Girl Names Starting with S — Sara, Safiya & More',
    href: '/blog/50-islamic-girl-names-starting-with-s',
    tag: 'Girl Names',
    tagBg: '#FCE8F0',
    tagText: '#A0305A',
    date: 'May 10, 2026',
    readTime: '6 min',
    arabicLetter: 'سـ',
    gradientFrom: '#4A2D6A',
    gradientTo: '#7A4FA5',
    excerpt: "The letter Seen gives us some of Islam's most beloved names — explore them all here.",
    category: 'girl',
    comingSoon: true,
  },
  {
    slug: 'can-muslims-use-non-arabic-names',
    title: 'Can Muslims Use Non-Arabic Names? A Scholarly Perspective',
    href: '/blog/can-muslims-use-non-arabic-names',
    tag: 'Naming Guide',
    tagBg: '#F0DEB0',
    tagText: '#7A5A10',
    date: 'May 5, 2026',
    readTime: '4 min',
    arabicLetter: 'دـ',
    gradientFrom: '#1C3A2E',
    gradientTo: '#3D7A5E',
    excerpt: 'Persian, Turkish, Urdu names — are they permissible? Islamic scholars weigh in on the matter.',
    category: 'tips',
    comingSoon: true,
  },
  {
    slug: 'names-of-the-prophets-in-islam',
    title: 'Names of the Prophets in Islam — Meanings and Stories',
    href: '/blog/names-of-the-prophets-in-islam',
    tag: 'Boy Names',
    tagBg: '#E3EEF9',
    tagText: '#1A4F8A',
    date: 'April 28, 2026',
    readTime: '8 min',
    arabicLetter: 'يـ',
    gradientFrom: '#1A3A1A',
    gradientTo: '#2D6A2D',
    excerpt: 'From Adam to Muhammad ﷺ — the names of all 25 Prophets mentioned in the Quran, explained.',
    category: 'boy',
    comingSoon: true,
  },
  {
    slug: 'the-name-fatima-meaning-history',
    title: 'The Name Fatima — Meaning, History, and Why It Matters',
    href: '/blog/the-name-fatima-meaning-history',
    tag: 'Girl Names',
    tagBg: '#FCE8F0',
    tagText: '#A0305A',
    date: 'April 20, 2026',
    readTime: '5 min',
    arabicLetter: 'هـ',
    gradientFrom: '#5A1A2A',
    gradientTo: '#A0304A',
    excerpt: 'The most beloved name in Islam. Learn the full story, meaning, and legacy of Fatimah bint Muhammad.',
    category: 'girl',
    comingSoon: true,
  }
];
